name: federlieb-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          push: never
          runCmd: |
            .vscode/setup.sh
            cmake \
              -DCMAKE_MODULE_PATH=/workspaces/federlieb/build \
              -DCMAKE_BUILD_TYPE=Debug \
              -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
              -S/workspaces/federlieb \
              -B/workspaces/federlieb/build \
              -G Ninja
            cmake --build build --config Debug --target fl_extensions --
            . .venv/bin/activate
            pytest tests
